-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USERLIDER', 'USERSUPERVISOR', 'USERCENTRAL', 'USERPASTOR', 'MEMBER', 'ADMIN');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'MEMBER';
